language: julia
os:
  - linux
julia:
  - 0.4
notifications:
  email: false
addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - xserver-xorg-video-dummy
    - xpra
    - cmake
    - libxxf86vm-dev
    sources:
    - kubuntu-backports
before_script:
  - "xpra --xvfb=\"Xorg +extension GLX +extension RANDR +extension RENDER -config `pwd`/test/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log\"  start :9"
  - "export DISPLAY=:9 glvisualize test"
after_script:
  - "xpra stop :9"
  - "cat ~/.xpra/*"
