language: julia
os:
  - linux
julia:
  - 0.4
notifications:
  email: false
addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - xserver-xorg-video-dummy
    - cmake
    - libxxf86vm-dev
    sources:
    - kubuntu-backports
before_script:
  - "export DISPLAY=:99.0"
  - "Xorg -noreset +extension GLX +extension RANDR +extension RENDER" # X virtual framebuffer


script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - xvfb-run julia -e 'Pkg.clone(pwd()); Pkg.test("GLVisualize")'
