language: julia
os:
  - linux
julia:
  - 0.4
notifications:
  email: false
addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - xvfb
    - xauth
    - cmake
    - libxxf86vm-dev
    sources:
    - kubuntu-backports
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" # X virtual framebuffer
